name: compiler-rt package build

on:
  push:
    branches:
      - main
env:
  GITHUB_USERNAME: dakkshesh07
  GITHUB_EMAIL: dakkshesh5@gmail.com
  PKG_VER: 15.0.2
  REL_VER: 1
  GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
          gh auth login --with-token <<< $GHUB_TOKEN
      - name: Build
        run: |
          curl -fsSL "https://pkgbuild.com/~morganamilo/pacman-static/x86_64/bin/pacman-static" -o pacman-static && chmod +x pacman-static && mv pacman-static /usr/bin/
          pip uninstall -y pytz setuptools appdirs && pacman-static -Syu --needed --noconfirm python-sphinx python-recommonmark openmp swig libffi libedit ncurses libxml2 python-setuptools python-psutil
          cd compiler-rt
          sed -i '/E_ROOT/d' /usr/bin/makepkg && makepkg -s
          git clone https://github.com/Neutron-Toolchains/llvm-pkgbuild.git rel-repo
          mv *.pkg.tar.zst rel-repo/
          cd rel-repo/
          export PACK_VER="$PKG_VER-$REL_VER"
          curl -s https://bin.cyberknight777.dev/ojhW/raw | bash
