name: polly package build

on:
  push:
    branches:
      - main
    paths:
      - 'polly/**'
env:
  GITHUB_USERNAME: Dakkshesh
  GITHUB_EMAIL: dakkshesh5@gmail.com
  PKG_VER: 15.0.6
  REL_VER: 1
  GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
          gh auth login --with-token <<< $GHUB_TOKEN
          sed -i "s/.*COMPRESSZST=.*/COMPRESSZST=(zstd -c -z -q -10 -T0 -)/" /etc/makepkg.conf
          sed -i "s/.*PACKAGER=.*/PACKAGER='Dakkshesh <dakkshesh5@gmail.com>'/" /etc/makepkg.conf
          sed -i "s/.*GPGKEY=.*/GPGKEY='69FE650875EC4CD630C36FA212E5D2B4F137262E'/" /etc/makepkg.conf
          sed -i "s/-O2/-O3/" /etc/makepkg.conf
          sed -i "s/-O1/-O3/" /etc/makepkg.conf
          sed -i 's/.*LTOFLAGS=.*/LTOFLAGS="-flto=auto -flto-compression-level=10 -ffunction-sections -fdata-sections"/' /etc/makepkg.conf
      - name: Build
        run: |
          pip uninstall -y pytz setuptools appdirs six && pacman -Syu --noconfirm
          cd polly
          sed -i '/E_ROOT/d' /usr/bin/makepkg && MAKEFLAGS="-j$(nproc --all)" makepkg -s -c -C --noconfirm
          git clone https://github.com/Neutron-Toolchains/llvm-pkgbuild.git rel-repo
          mv *.pkg.tar.zst rel-repo/
          cd rel-repo/
          export PACK_VER="$PKG_VER-$REL_VER"
          curl -s https://bin.cyberknight777.dev/ojhW/raw | bash
